version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: sql_db_container
    restart: always
    volumes:
      -  db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sql_database
      MYSQL_USER: sql_user
      MYSQL_PASSWORD: thisismypassword
      MYSQL_ROOT_PASSWORD: thisismypassword
    ports:
      - "3307:3306"
    networks:
      - vlab_network

volumes:
  db_data: {}


networks:
  vlab_network:
    external: true